openapi: 3.0.0
info:
  title: Physical AI Book API
  version: 1.0.0
paths:
  /chapters:
    get:
      summary: Get all chapters
      responses:
        '200':
          description: A list of chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'
  /chapters/{slug}:
    get:
      summary: Get a single chapter
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single chapter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
components:
  schemas:
    Chapter:
      type: object
      properties:
        title:
          type: string
        slug:
          type: string
        summary:
          type: string
        modules:
          type: array
          items:
            $ref: '#/components/schemas/Module'
    Module:
      type: object
      properties:
        title:
          type: string
        slug:
          type: string
        content:
          type: string
        example:
          type: string
        exercise:
          type: string
