// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  aiBookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [{ type: 'autogenerated', dirName: '00-intro' }]
    },

    {
      type: 'category',
      label: 'Module 1 — ROS 2 Fundamentals',
      items: [
        { type: 'autogenerated', dirName: '01-ros-fundamentals' }
      ],
    },

    {
      type: 'category',
      label: 'Module 2 — Digital Twin (Gazebo & Unity)',
      items: [
        { type: 'autogenerated', dirName: '02-digital-twin' }
      ],
    },

    {
      type: 'category',
      label: 'Module 3 — NVIDIA Isaac AI',
      items: [
        { type: 'autogenerated', dirName: '03-nvidia-isaac' }
      ],
    },

    {
      type: 'category',
      label: 'Module 4 — Vision-Language-Action (VLA)',
      items: [
        { type: 'autogenerated', dirName: '04-vla-integration' }
      ],
    },

    {
      type: 'category',
      label: 'Capstone Project — The Autonomous Humanoid',
      items: [{ type: 'autogenerated', dirName: '05-capstone' }]
    },
  ],
};

export default sidebars;
